Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.provider "qemu" do |qemu|
    qemu.memory = "4096"
    qemu.cpus = "2"
    qemu.machine = "virt,accel=hvf"
  end
end
