---
- name: Install Softwares
- hosts: localhost
  vars:
    packages: 
       - name: nignx
         required: true 
       - name: mysql
         required: true 
       - name: apache
         required: false 
  tasks:
  - name: Install "{{item.name}}" on Debian
    apt:
      name: "{{item.name}}"
      state: present
    when: item.required == true
    loop: "{{packages}}"
