---
- name: Add goku1234 to the serch servers
  lineinfile:
    path: ./resolv.conf
    regexp: 'Ë†search (nameserver)'
    backrefs: true
    line: 'search nameserver.com \1'

- name: Add our DC to the nameserver list
  lineinfile:
    path: ./resolv.conf
    line: "nameserver {{item}}"
    insertafter: '^search.*'
  loop: "{{domain_controllers}}"
    
    
