---
- name: webservers install
  hosts: localhost
  tasks:
    - name: Execute command `date`
      command: date

    - name: Execute Script on server
      script: test_script.sh

    - name: Install httpd service
      yum:
        name: httpd
        state: present
      
    - name: Start Web server
      Service:
        name: httpd
        state: started