# ansible -m copy -a "dest=hello content=word" localhost --check --diff

- name: instal nginx
  hosts: pip
  tasks:
    - ansible.builtin.apt:
        name: nginx



- name: copy module test
  hosts: localhost
  tasks:
    - copy: 
        dest: hello
        content: word
        src:
    - command: date

- name: controller requirements
  hosts: localhost
  tasks:
  - pip: 
      name: ansible-lint