all:
  hosts:
    Webserver01:
      ansible_user: ec2-user
      ansible_host: ec2-3-91-104-177.compute-1.amazonaws.com #172.31.40.59
      ansible_ssh_private_key_file: hostkey.pem

    Webserver02:
      ansible_user: ec2-user
      ansible_host: ec2-3-81-135-168.compute-1.amazonaws.com #172.31.34.250
      ansible_ssh_private_key_file: hostkey.pem
  children:
    webservers:
      hosts:
        Webserver01: {}
        Webserver02: {}
