all:
  hosts:
    Webserver01:
      ansible_user: ubuntu
      ansible_host: ec2-18-208-172-181.compute-1.amazonaws.com #172.31.40.59
      ansible_ssh_private_key_file: hostkey.pem

    Webserver02:
      ansible_user: ubuntu
      ansible_host: ec2-54-81-244-211.compute-1.amazonaws.com #172.31.34.250
      ansible_ssh_private_key_file: hostkey.pem
  children:
    webservers:
      hosts:
        Webserver01: {}
        Webserver02: {}
